import { createHash, createCipheriv, createDecipheriv, randomBytes, timingSafeEqual } from 'node:crypto';
import { initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { defineSecret } from 'firebase-functions/params';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { setGlobalOptions } from 'firebase-functions/v2';
import { addDays, calculateEntry, hash, id, monday, nextMonday, rateAt, today, validDate } from '../lib/domain.mjs';

initializeApp();
setGlobalOptions({ region: 'asia-southeast1', maxInstances: 3, memory: '256MiB', timeoutSeconds: 30 });
const db = getFirestore();
const authAdmin = getAuth();
const ADMIN_PIN = defineSecret('NIYET_ADMIN_PIN');
const INVITE_SECRET = defineSecret('NIYET_INVITE_SECRET');
const groups = db.collection('groups');
const activities = db.collection('activities');
const security = db.collection('security');
const defaults = [
  ['quran','Құран','pages',100],['tafsir','Құран тәпсірі (RNK)','pages',150],['book','Кітап','pages',80],
  ['tahajjud','Тәһәжжүд','done',1000],['duha','Дұха','done',800],['awabeen','Әууәбин','done',600],['fasting','Ораза','done',1200]
];
const problem = (code, message) => { throw new HttpsError(code, message); };
const clean = (v,max,label) => { if(typeof v!=='string'||!v.trim()||v.trim().length>max)problem('invalid-argument',label);return v.trim(); };
const digest=value=>createHash('sha256').update(String(value)).digest('hex');
const nowDate=()=>today();
async function seed(){
 const ref=db.doc('system/initialized');
 await db.runTransaction(async tx=>{
  const marker=await tx.get(ref);if(marker.exists)return;
  for(const [i,name] of ['Достар','Оқу тобы'].entries())tx.create(groups.doc('group'+(i+1)),{id:'group'+(i+1),name,inviteHash:null,inviteEncrypted:null,createdAt:Date.now()});
  for(const [activityId,title,unit,points] of defaults)tx.create(activities.doc(activityId),{id:activityId,title,unit,activeFrom:'2000-01-01',rules:[{from:'2000-01-01',points}]});
  tx.create(ref,{createdAt:Date.now(),schema:1});
 });
}
function caller(req){if(!req.auth?.uid)problem('unauthenticated','Қауіпсіз кіру басталмады. Бетті жаңартып көр.');return req.auth.uid;}
async function memberFor(groupId,uid){if(!groupId)problem('failed-precondition','Топтың шақыру сілтемесін аш.');const ref=groups.doc(groupId),group=await ref.get();if(!group.exists)problem('not-found','Топ табылмады.');const m=await ref.collection('members').doc(uid).get();return{ref,group:group.data(),member:m.exists?{id:uid,...m.data()}:null};}
function adminFor(req){const token=req.auth?.token;if(!token?.admin||!Number.isInteger(token.adminUntil)||token.adminUntil<Date.now())problem('permission-denied','Әкімші ретінде қайта кір.');return req.auth.uid;}
async function limited(req,bucket,max,windowMs){const uid=req.auth?.uid||'anonymous',ip=String(req.rawRequest?.headers?.['x-forwarded-for']||'').split(',')[0]||uid,key=digest(bucket+':'+ip),ref=security.doc(key);return db.runTransaction(async tx=>{const snap=await tx.get(ref),now=Date.now(),old=snap.data();if(old&&old.until>now&&old.count>=max)return false;tx.set(ref,old&&old.until>now?{count:old.count+1,until:old.until}:{count:1,until:now+windowMs});return true;});}
function seal(value){const key=createHash('sha256').update(INVITE_SECRET.value()).digest(),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return[iv,cipher.getAuthTag(),data].map(x=>x.toString('base64url')).join('.');}
function unseal(value){const key=createHash('sha256').update(INVITE_SECRET.value()).digest(),[iv,tag,data]=value.split('.').map(x=>Buffer.from(x,'base64url')),decipher=createDecipheriv('aes-256-gcm',key,iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8');}
async function snapshot(groupId,week){const group=groups.doc(groupId),[g,members,entries,comments]=await Promise.all([group.get(),group.collection('members').get(),group.collection('entries').where('date','>=',week).where('date','<',addDays(week,7)).get(),group.collection('comments').where('week','==',week).get()]);const entryData=entries.docs.map(d=>d.data()),commentMap=new Map(comments.docs.map(d=>[d.data().memberId,d.data().text])),list=members.docs.map(doc=>{const m=doc.data(),score=entryData.filter(e=>e.memberId===doc.id).reduce((n,e)=>n+e.score,0);return{id:doc.id,name:m.name,score,comment:commentMap.get(doc.id)||''}}).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'kk'));let previous=null,place=0;const ranked=list.map((m,i)=>{if(m.score!==previous)place=i+1;previous=m.score;return{...m,place}});return{group:g.data(),members:members.docs,entries:entryData,ranking:ranked};}
async function run(req){
 await seed();const uid=caller(req),data=req.data||{},method=data.method||'GET',input=data.body||{},url=new URL(data.path||'/','https://niyet.local'),path=url.pathname.replace(/\/$/,'')||'/',groupId=data.groupId;
 if(!['GET','POST','PUT'].includes(method))problem('invalid-argument','Бұл әрекет қолжетімсіз.');
 if(path==='/session'&&method==='GET'){const found=groupId?await memberFor(groupId,uid):null,claims=req.auth.token;return{today:nowDate(),week:monday(),admin:Boolean(claims.admin&&Number.isInteger(claims.adminUntil)&&claims.adminUntil>Date.now()),member:found?.member?{id:uid,name:found.member.name}:null,group:found?.member?{id:groupId,name:found.group.name}:null};}
 if(path==='/invite'&&method==='GET'){const token=url.searchParams.get('token')||'';if(token.length<30||token.length>100)problem('not-found','Шақыру сілтемесі жарамсыз немесе жаңартылған.');const found=await groups.where('inviteHash','==',hash(token)).limit(1).get();if(found.empty)problem('not-found','Шақыру сілтемесі жарамсыз немесе жаңартылған.');const doc=found.docs[0],isMember=(await doc.ref.collection('members').doc(uid).get()).exists;return{name:doc.get('name'),groupId:doc.id,existingMember:isMember};}
 if(path==='/join'&&method==='POST'){if(!await limited(req,'join',15,15*60*1000))problem('resource-exhausted','Біраз уақыттан кейін қайталап көр.');const token=input.token||'',found=await groups.where('inviteHash','==',hash(token)).limit(1).get();if(found.empty)problem('not-found','Шақыру сілтемесі жарамсыз.');const group=found.docs[0],name=clean(input.name,40,'Атыңды енгіз (40 таңбаға дейін).'),memberRef=group.ref.collection('members').doc(uid),duplicates=group.ref.collection('members').where('nameKey','==',name.toLocaleLowerCase('kk')).limit(1);await db.runTransaction(async tx=>{const[old,dup]=await Promise.all([tx.get(memberRef),tx.get(duplicates)]);if(old.exists)return;if(!dup.empty)problem('already-exists','Бұл ат топта бар. Атыңа тегіңді немесе басқа белгі қос.');tx.create(memberRef,{name,nameKey:name.toLocaleLowerCase('kk'),joinedAt:Date.now()});});return{joined:true,groupId:group.id};}
 if(path==='/tracker'&&method==='GET'){const{ref,group,member}=await memberFor(groupId,uid);if(!member)problem('permission-denied','Топқа қосылу үшін шақыру сілтемесін аш.');const week=url.searchParams.get('week')||monday(),date=url.searchParams.get('date')||nowDate();if(!validDate(week)||monday(week)!==week||week>monday()||!validDate(date)||date<week||date>=addDays(week,7)||date>nowDate())problem('invalid-argument','Апта немесе күн дұрыс таңдалмаған.');const[acts,entryDoc,weekData]=await Promise.all([activities.get(),ref.collection('entries').doc(uid+'_'+date).get(),snapshot(groupId,week)]);return{today:nowDate(),week,member:{id:uid,name:member.name},group:{name:group.name,memberCount:weekData.members.length},activities:acts.docs.map(d=>d.data()).filter(a=>a.activeFrom<=date).map(a=>({id:a.id,title:a.title,unit:a.unit,points:rateAt(a,date)})),entry:entryDoc.exists?entryDoc.data():null,weekEntries:weekData.entries.filter(e=>e.memberId===uid),ranking:weekData.ranking};}
 if(path==='/entry'&&method==='PUT'){const{ref,member}=await memberFor(groupId,uid),date=input.date;if(!member)problem('permission-denied','Топқа қосылу үшін шақыру сілтемесін аш.');if(!validDate(date)||date<monday()||date>nowDate())problem('invalid-argument','Тек осы аптаның өткен күндерін өзгертуге болады.');const acts=await activities.get(),state={activities:acts.docs.map(d=>d.data())},entryRef=ref.collection('entries').doc(uid+'_'+date);let entry;try{entry=await db.runTransaction(async tx=>{const old=await tx.get(entryRef),value=calculateEntry(state,{id:uid,groupId},date,input.values,old.exists?old.data():null);tx.set(entryRef,value);return value;});}catch(e){if(e instanceof HttpsError)throw e;problem('invalid-argument',e.message||'Жазба дұрыс емес.');}return{entry};}
 if(path==='/admin/login'&&method==='POST'){if(!await limited(req,'pin',5,15*60*1000))problem('resource-exhausted','Тым көп әрекет. 15 минуттан кейін қайтала.');const expected=Buffer.from(digest(ADMIN_PIN.value())),actual=Buffer.from(digest(String(input.pin||'')));if(!timingSafeEqual(expected,actual))problem('unauthenticated','PIN дұрыс емес.');const user=await authAdmin.getUser(uid),claims={...user.customClaims,admin:true,adminUntil:Date.now()+8*3600*1000};await authAdmin.setCustomUserClaims(uid,claims);return{admin:true};}
 if(path==='/admin/logout'&&method==='POST'){const user=await authAdmin.getUser(uid),claims={...user.customClaims};delete claims.admin;delete claims.adminUntil;await authAdmin.setCustomUserClaims(uid,claims);return{loggedOut:true};}
 if(path.startsWith('/admin')){adminFor(req);
  if(path==='/admin'&&method==='GET'){const week=url.searchParams.get('week')||monday();if(!validDate(week)||monday(week)!==week||week>monday())problem('invalid-argument','Апта дұрыс таңдалмаған.');const[gs,acts]=await Promise.all([groups.get(),activities.get()]),all=await Promise.all(gs.docs.map(async doc=>{const snap=await snapshot(doc.id,week);return{id:doc.id,name:doc.get('name'),memberCount:snap.members.length,invite:doc.get('inviteEncrypted')?unseal(doc.get('inviteEncrypted')):null,ranking:snap.ranking};}));return{week,nextWeek:nextMonday(),groups:all,activities:acts.docs.map(d=>{const a=d.data();return{id:a.id,title:a.title,unit:a.unit,points:rateAt(a,nowDate()),nextPoints:rateAt(a,nextMonday())};})};}
  if(path==='/admin/invite'&&method==='POST'){const g=groups.doc(input.groupId),doc=await g.get();if(!doc.exists)problem('not-found','Топ табылмады.');const raw=randomBytes(32).toString('base64url');await g.update({inviteHash:hash(raw),inviteEncrypted:seal(raw)});return{invite:raw};}
  if(path==='/admin/group'&&method==='PUT'){const name=clean(input.name,50,'Топ атауын енгіз.'),g=groups.doc(input.groupId);if(!(await g.get()).exists)problem('not-found','Топ табылмады.');await g.update({name});return{updated:true};}
  if(path==='/admin/activity'&&method==='POST'){const title=clean(input.title,70,'Атауды енгіз (70 таңбаға дейін).');if(!['pages','done'].includes(input.unit)||!Number.isInteger(input.points)||input.points<0||input.points>100000)problem('invalid-argument','Ұпай немесе өлшем дұрыс емес.');const existing=await activities.where('titleKey','==',title.toLocaleLowerCase('kk')).limit(1).get();if(!existing.empty)problem('already-exists','Бұл атау бар.');const activityId=id(),now=nowDate();await activities.doc(activityId).create({id:activityId,title,titleKey:title.toLocaleLowerCase('kk'),unit:input.unit,activeFrom:now,rules:[{from:now,points:input.points}]});return{added:true};}
  if(path==='/admin/rules'&&method==='PUT'){if(!input.rates||typeof input.rates!=='object'||Array.isArray(input.rates))problem('invalid-argument','Ұпай ережелері дұрыс емес.');const docs=await activities.get(),changes=[];for(const d of docs.docs){const a=d.data(),points=input.rates[a.id];if(!Number.isInteger(points)||points<0||points>100000)problem('invalid-argument','Ұпай бүтін, теріс емес сан болуы керек.');if(rateAt(a,nextMonday())!==points){const rules=a.rules.filter(r=>r.from!==nextMonday());rules.push({from:nextMonday(),points});changes.push([d.ref,rules]);}}const batch=db.batch();for(const[ref,rules]of changes)batch.update(ref,{rules});await batch.commit();return{effectiveFrom:nextMonday()};}
  if(path==='/admin/comment'&&method==='PUT'){const week=input.week;if(!validDate(week)||monday(week)!==week||week>monday()||typeof input.text!=='string'||input.text.length>500)problem('invalid-argument','Пікір 500 таңбадан аспасын.');const g=groups.doc(input.groupId),member=await g.collection('members').doc(input.memberId).get();if(!member.exists)problem('not-found','Қатысушы табылмады.');await g.collection('comments').doc(input.memberId+'_'+week).set({groupId:input.groupId,memberId:input.memberId,week,text:input.text.trim(),updatedAt:Date.now()});return{saved:true};}
 }
 problem('not-found','Бет табылмады.');
}
export const niyetApi=onCall({secrets:[ADMIN_PIN,INVITE_SECRET]},run);
